"""empty message

Revision ID: 186ad399d56c
Revises: 717532e4fe33
Create Date: 2020-05-05 12:25:41.659022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186ad399d56c'
down_revision = '717532e4fe33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('skype', sa.String(length=35), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'skype')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###
