"""empty message

Revision ID: 717532e4fe33
Revises: 91519ed0751f
Create Date: 2020-05-02 22:40:37.702497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717532e4fe33'
down_revision = '91519ed0751f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_type', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
