"""empty message

Revision ID: 752e6a2ebb06
Revises: d5b73963a842
Create Date: 2020-05-13 10:55:13.102131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752e6a2ebb06'
down_revision = 'd5b73963a842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bl_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bl_token',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='bl_token_pkey')
    )
    # ### end Alembic commands ###
